run without checks

diff --git a/.github/workflows/next-build-image.yaml b/.github/workflows/next-build-image.yaml
--- a/.github/workflows/next-build-image.yaml
+++ b/.github/workflows/next-build-image.yaml
@@ -32,9 +32,9 @@ jobs:
           fetch-depth: 0
           ref: ${{ github.sha }}
 
-      - name: Check Image and Relevant Changes
-        id: check-image
-        uses: ./.github/actions/check-image-and-changes
+      # - name: Check Image and Relevant Changes
+      #   id: check-image
+      #   uses: ./.github/actions/check-image-and-changes
 
       - name: Setup Node.js
         uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
@@ -69,9 +69,9 @@ jobs:
           fetch-depth: 0
           ref: ${{ github.base_ref }} #${{ github.event.pull_request.head.sha }}
 
-      - name: Check Image and Relevant Changes
-        id: check-image
-        uses: ./.github/actions/check-image-and-changes
+      # - name: Check Image and Relevant Changes
+      #   id: check-image
+      #   uses: ./.github/actions/check-image-and-changes
 
       - name: Setup Node.js
         uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
@@ -90,20 +90,21 @@ jobs:
         with:
           cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}
 
-      - name: Run prettier
-        run: yarn prettier:check --continue --affected
+      # - name: Run prettier
+      #   run: yarn prettier:check --continue --affected
 
-      - name: Run lint
-        run: yarn run lint:check --continue --affected
+      # - name: Run lint
+      #   run: yarn run lint:check --continue --affected
 
-      - name: Run monorepo tools
-        run: yarn run monorepo:check
+      # - name: Run monorepo tools
+      #   run: yarn run monorepo:check
 
-      - name: Regenerate dockerfiles
-        run: |
-          yarn run build:dockerfile; if [[ $(git diff --name-only | grep Dockerfile || true) != "" ]]; then \
-            echo "ERROR: Workspace is dirty! Must run 'yarn build:dockerfile' and commit changes!"; exit 1; \
-          fi
+      # - name: Regenerate dockerfiles
+      #   run: |
+      #     yarn run build:dockerfile; if [[ $(git diff --name-only | grep Dockerfile || true) != "" ]]; then \
+      #       echo "ERROR: Workspace is dirty! Must run 'yarn build:dockerfile' and commit changes!"; exit 1; \
+      #     fi
+
       - name: Run tests
         run: yarn run test --continue --affected
 
